spring:
  application:
    name:helium-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否从Eureka Server中获取注册信息，默认是true
    fetch-registry: false
    #表示是否将自己注册到Eureka Server，默认是true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8000/eureka/